

create table if not exists desktop_computer (
    id int generated by default as identity primary key,
    serial_number varchar not null unique,
    manufacturer varchar,
    price float check ( price > 0 ),
    stock_quantity int check ( stock_quantity > 0 ),
    type varchar not null
);

create table if not exists computer_monitor(
    id int generated by default as identity primary key,
    serial_number varchar not null unique,
    manufacturer varchar,
    price float check ( price > 0 ),
    stock_quantity int check ( stock_quantity > 0 ),
    diagonal float not null
);


create table if not exists hard_drive(
    id int generated by default as identity primary key,
    serial_number varchar not null unique,
    manufacturer varchar,
    price float check ( price > 0 ),
    stock_quantity int check ( stock_quantity > 0 ),
    capacity int not null
);

create table if not exists laptop(
    id int generated by default as identity primary key,
    serial_number varchar not null unique,
    manufacturer varchar,
    price float check ( price > 0 ),
    stock_quantity int check ( stock_quantity > 0 ),
    size int not null
);

