

create table if not exists desktop_computer (
                                                id int generated by default as identity primary key,
                                                serial_number varchar not null unique,
                                                manufacturer varchar,
                                                price float check ( price > 0 ),
                                                stock_quantity int check ( stock_quantity > 0 ),
                                                type varchar not null
);

create table if not exists computer_monitor(
                                               id int generated by default as identity primary key,
                                               serial_number varchar not null unique,
                                               manufacturer varchar,
                                               price float check ( price > 0 ),
                                               stock_quantity int check ( stock_quantity > 0 ),
                                               diagonal float not null
);


create table if not exists hard_drive(
                                         id int generated by default as identity primary key,
                                         serial_number varchar not null unique,
                                         manufacturer varchar,
                                         price float check ( price > 0 ),
                                         stock_quantity int check ( stock_quantity > 0 ),
                                         capacity int not null
);

create table if not exists laptop(
                                     id int generated by default as identity primary key,
                                     serial_number varchar not null unique,
                                     manufacturer varchar,
                                     price float check ( price > 0 ),
                                     stock_quantity int check ( stock_quantity > 0 ),
                                     size int not null
);

insert into desktop_computer (serial_number, manufacturer, price, stock_quantity, type)
values ('890786543', 'Shegn-Jang.Ltd', 340.50, 2, 'desktop');
insert into desktop_computer (serial_number, manufacturer, price, stock_quantity, type)
values ('890356273', 'Acer Inc.', 403.50, 5, 'AIO');
insert into desktop_computer (serial_number, manufacturer, price, stock_quantity, type)
values ('320463827', 'Dell', 450.80, 4, 'nettop');

insert into laptop (serial_number, manufacturer, price, stock_quantity, size)
values ('90L65D67TD', 'HP Inc.', 506.30, 2, 17);
insert into laptop (serial_number, manufacturer, price, stock_quantity, size)
values ('986TD56L97', 'Asus', 486.90, 3, 15);
insert into laptop (serial_number, manufacturer, price, stock_quantity, size)
values ('90O674ED65', 'Apple Inc.', 1509.60, 3, 17);

insert into computer_monitor (serial_number, manufacturer, price, stock_quantity, diagonal)
values ('578T43F457', 'LG', 309.70, 9, 17);
insert into computer_monitor (serial_number, manufacturer, price, stock_quantity, diagonal)
values ('908T43E39M', 'Acer', 450.90, 8, 21.5);
insert into computer_monitor (serial_number, manufacturer, price, stock_quantity, diagonal)
values ('87YN5634V7', 'Xiaomi', 560.70, 12, 30);

insert into hard_drive (serial_number, manufacturer, price, stock_quantity, capacity)
values ('890OL7643G', 'Seagate Technology', 125.80, 6, 6);
insert into hard_drive (serial_number, manufacturer, price, stock_quantity, capacity)
values ('095GT43D65', 'Toshiba', 40.60, 10, 1);
insert into hard_drive (serial_number, manufacturer, price, stock_quantity, capacity)
values ('KU7645DB78', 'Western Digital', 38.50, 12, 1);